
    @startuml
    class DataController {
        +loginUser()
        +sendNewGhostNetData()
        +sumEntriesInDBByStatus()
        +getAllRecoveredGhostNetsByUserId()
        +getGhostNetBeanById()
        +getAllGhostNets()
        +getAttributesFromDBUsers()
        +createReportForGhostNet()
        +getSnippetForMapMarker()
        +getLatestGhostNetId()
        +getReportsByUserId()
        +getLabelById()
        +getCurrentUnixTime()
        +getDurationHumanReadable()
        +getLabelForPositionFromCache()
        +getLabelForPositionFromService()
        +saveGeoNameResultToCache()
        +getGhostNetsByStatusId()
    }
    DataController --> DataService: uses
    DataController --> DataServiceGeoNames: uses
    DataController --> GhostNetBean: uses
    DataController --> ReportBean: uses
    DataController --> ServerBean: uses
    DataController --> StatisticBean: uses
    DataController --> LoginBean: uses
    @enduml
    