
    @startuml
    class DataServiceGeoNames {
        +getPositionLabelFromService()
        +getLabelForPositionFromCache()
        +saveGeoNameResultToCache()
        +getCurrentUnixTime()
    }
    @enduml
    