
    @startuml
    class GhostNetBean {
        +getId()
        +setId()
        +getPosLatitude()
        +setPosLatitude()
        +getPosLongitude()
        +setPosLongitude()
        +getSize()
        +setSize()
        +getAllGhostNets()
        +getGhostNetsByStatusId()
        +getGhostNetsReportedMissing()
        +submitData()
        +getFirstReportBean()
        +setFirstReportBean()
        +getLatestReportBean()
        +setLatestReportBean()
        +createReport()
        +getSnippetForMapMarker()
        +getLatestId()
        +setStatusToReported()
        +setStatusToSalvagePending()
        +Recovered()
        +setStatusToReportedMissing()
        +setStatusToMissing()
        +getSizeLabel()
        +getAgeOfReport()
        +getReportsByUserId()
        +getLabelForPosition()
        +getAllActiveGhostNets()
        +getAllRecoveredGhostNetsByUserId()
        +getDetailsForMapMarker()
        +getViewDetailsLink()
    }
    @enduml
    