
    @startuml
    class ServerBean {
        +getStartTime()
        +setRequestCounterUpByOne()
        +getRequestCounter()
        +sumEntriesinDBByStatus()
        +getDebugMode()
        +setDebugMode()
    }
    @enduml
    