
    @startuml
    class StatisticBean {
        +getGhostNetsInDB()
        +getGhostNetsWithStatusReported()
        +getGhostNetsWithStatusSalvagePending()
        +getGhostNetsWithStatusRecovered()
        +getGhostNetsWithStatusReportedMissing()
        +getGhostNetsWithStatusMissing()
    }
    @enduml
    